# Generated by Django 4.0.1 on 2022-05-14 16:13

import backend.models
import d3_bakcend.utils.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionEdges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('origin_file_id', models.IntegerField(default=1)),
                ('source', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
                ('sourceFile', models.CharField(default='', max_length=150, null=True)),
                ('sourcePackageName', models.CharField(default='', max_length=100, null=True)),
                ('sourceIsHonor', models.SmallIntegerField(default=0)),
                ('targetFile', models.CharField(default='', max_length=150, null=True)),
                ('targetPackageName', models.CharField(default='', max_length=100, null=True)),
                ('targetIsHonor', models.SmallIntegerField(default=0)),
                ('value', models.CharField(default='', max_length=30, null=True, verbose_name='依赖关系')),
                ('mode_type', models.CharField(default='', max_length=50, null=True, verbose_name='模式类型')),
            ],
            options={
                'verbose_name': '依赖切面边',
                'verbose_name_plural': '依赖切面边',
                'db_table': '依赖切面边表',
            },
        ),
        migrations.CreateModel(
            name='SectionNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('origin_file_id', models.IntegerField(default=1)),
                ('_id', models.IntegerField(default=0)),
                ('isHonor', models.SmallIntegerField(default=0)),
                ('category', models.CharField(default='', max_length=30)),
                ('qualifiedName', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=100)),
                ('File', models.CharField(default='', max_length=150, null=True)),
                ('packageName', models.CharField(default='', max_length=100, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('modifiers', models.CharField(max_length=30, null=True)),
                ('_global', models.BooleanField(null=True)),
                ('mode_type', models.CharField(default='', max_length=100, null=True, verbose_name='模式类型')),
            ],
            options={
                'verbose_name': '依赖切面结点',
                'verbose_name_plural': '依赖切面结点',
                'db_table': '依赖切面结点表',
            },
        ),
        migrations.CreateModel(
            name='SectionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('file_extension', models.CharField(default='', max_length=10, verbose_name='文件类型')),
                ('file_name', models.CharField(default='', max_length=100, verbose_name='文件名称')),
                ('status', models.BooleanField(null=True, verbose_name='是否解析')),
                ('file', models.FileField(default='', max_length=120, null=True, storage=d3_bakcend.utils.storage.MinioStorage(), upload_to=backend.models.sectionFiles_folder_path, verbose_name='文件')),
                ('section_type', models.SmallIntegerField(default=1)),
                ('mode_type', models.CharField(default='', max_length=100, verbose_name='模式类型')),
                ('qualifiedName', models.CharField(default='', max_length=200)),
                ('end', models.BooleanField(blank=True, default=False, null=True)),
                ('subEnd', models.BooleanField(blank=True, default=False, null=True)),
                ('parent_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.sectionfiles', verbose_name='上级文件')),
            ],
            options={
                'verbose_name': '依赖切面文件',
                'verbose_name_plural': '依赖切面文件',
                'db_table': '依赖切面文件表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('file_extension', models.CharField(default='', max_length=10, verbose_name='文件类型')),
                ('file_name', models.CharField(default='', max_length=100, verbose_name='文件名称')),
                ('status', models.BooleanField(null=True, verbose_name='是否解析')),
                ('file', models.FileField(default='', max_length=120, null=True, storage=d3_bakcend.utils.storage.MinioStorage(), upload_to=backend.models.projectFiles_folder_path, verbose_name='文件')),
                ('file_type', models.SmallIntegerField(null=True, verbose_name='文件类别')),
                ('parent_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.projectfiles', verbose_name='上级文件')),
            ],
            options={
                'verbose_name': '项目文件',
                'verbose_name_plural': '项目文件',
                'db_table': '项目文件表',
            },
        ),
        migrations.CreateModel(
            name='CatelogueTreeMapDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(default='', max_length=150, null=True, verbose_name='文件名称')),
                ('color', models.CharField(default='#FFFFFF', max_length=30, null=True, verbose_name='圆圈颜色')),
                ('relation', models.CharField(blank=True, default='', max_length=600, null=True, verbose_name='依赖变化')),
                ('end', models.BooleanField(blank=True, default=False, null=True)),
                ('value', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('qualifiedName', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='文件完整名称')),
                ('catelogue_type', models.SmallIntegerField(default=1, verbose_name='目录级别')),
                ('parent_catelogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.cateloguetreemapdatas', verbose_name='父类目录')),
                ('structure_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.projectfiles', verbose_name='结构文件')),
            ],
            options={
                'verbose_name': '目录树状数据表',
                'verbose_name_plural': '目录树状数据表',
                'db_table': '目录树状数据表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CatelogueDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(default='', max_length=150, null=True, verbose_name='文件名称')),
                ('color', models.CharField(default='#FFFFFF', max_length=30, null=True, verbose_name='圆圈颜色')),
                ('relation', models.CharField(blank=True, default='', max_length=600, null=True, verbose_name='依赖变化')),
                ('changeLoc', models.IntegerField(default=0, null=True, verbose_name='修改频率')),
                ('value', models.FloatField(default=0.0, null=True, verbose_name='半径')),
                ('catelogue_type', models.SmallIntegerField(choices=[(1, '一级目录'), (2, '二级目录')], default=1, verbose_name='目录级别')),
                ('parent_catelogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.cateloguedatas', verbose_name='父类目录')),
                ('structure_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.projectfiles', verbose_name='结构文件')),
            ],
            options={
                'verbose_name': '目录数据',
                'verbose_name_plural': '目录数据',
                'db_table': '目录数据表',
                'ordering': ['id'],
            },
        ),
    ]
